mod 'boxen',       '3.3.4', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew',    '1.4.1', :github_tarball => "boxen/puppet-homebrew"
mod 'respository', '2.2.0', :github_tarball => "boxen/puppet-repository"
mod 'stdlib',      '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'sysctl',      '1.0.0', :github_tarball => "boxen/puppet-sysctl"
